[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && cd client && npm install --include=dev && cd .. && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
